#!/usr/bin/env python3
"""Translate feature ids into short human-readable explanations."""

from __future__ import annotations

import re
from typing import Callable


EXACT_EXPLANATIONS: dict[str, str] = {
    "access.restriction_message": "The page shows an access restriction or block message.",
    "account_recovery_links": "The page includes account recovery links.",
    "anchor.external_captcha_link": "A CAPTCHA-related link points to an external destination.",
    "anchor.external_create_links": "Account-creation links go to an external destination.",
    "anchor.external_destination": "A link points to an external destination.",
    "anchor.external_destination_hint": "Link text suggests the destination is outside the site.",
    "anchor.external_login_signup_links": "Login or signup links point off-site.",
    "anchor.external_offsite_link": "A visible link sends the user to another site.",
    "anchor.external_reference": "The page references an external site through a link.",
    "anchor.external_unrelated_link": "A link points to an unrelated external domain.",
    "anchor.generic_support_links": "The page includes generic support or help links.",
    "anchor.js_link": "A link uses JavaScript instead of a normal destination.",
    "anchor.mismatched_link_target": "Link text does not match where the link actually goes.",
    "anchor.mismatched_login_host": "A login-related link points to a different host than expected.",
    "anchor.password_recovery": "The page includes a password recovery link.",
    "anchor.privacy_policy_placeholder": "A privacy-policy link appears to be a placeholder.",
    "anchor.uses_external_chat_domain": "The page uses an external chat provider.",
    "anchors.absent": "No links were observed on the page.",
    "anchors.account_navigation": "The page includes account-related navigation links.",
    "anchors.account_recovery_and_signup": "The page includes recovery or signup navigation.",
    "anchors.directory_navigation": "The page includes directory-style navigation.",
    "anchors.internal_navigation": "The page includes normal internal navigation links.",
    "anchors.offsite_redirect": "A link appears to redirect users off-site.",
    "anchors.store_navigation": "The page includes store or shopping navigation.",
    "anchors.total_observed": "This counts the number of observed links on the page.",
    "anchors_nonfunctional": "Some links appear nonfunctional or placeholder-like.",
    "auth.form_presence": "An authentication-related form is present.",
    "auth.login_form": "A login form is present.",
    "brand_imitating_content": "The content imitates a known brand or service.",
    "brand_like_login_ui": "The page looks like a branded login interface.",
    "brand_representation": "The page presents itself as a specific brand.",
    "branding.consistency": "Branding appears consistent across the page.",
    "branding.footer_copyright": "The footer includes a copyright or ownership claim.",
    "branding.inconsistent_links": "Branding does not align with the linked destinations.",
    "branding_metadata_inconsistency": "Branding in metadata does not match the rest of the page.",
    "certificate_encryption_claim": "The page claims certificate-based or encrypted security.",
    "challenge.anti_bot": "The page presents an anti-bot or human-check challenge.",
    "chat_widget_and_status_page": "The page includes chat or support-widget functionality.",
    "checkout_and_shipping_details": "The page asks for checkout or shipping details.",
    "cms_metadata.present": "The page exposes CMS or site-generator metadata.",
    "connection.https_redirect": "The site redirects users from HTTP to HTTPS.",
    "contact.chat_widget": "A chat-based contact option is present.",
    "contact.details.visible": "Contact details are visibly shown on the page.",
    "contact.email_mismatch": "The visible contact email does not match the site domain.",
    "contact.email_present": "An email contact is shown on the page.",
    "contact.form.present": "A contact form is present.",
    "contact.mailto_presence": "A mailto contact link is present.",
    "contact.methods.multiple": "The page provides multiple ways to make contact.",
    "contact.support_links": "The page provides support-related links.",
    "contact.transparency": "The page provides visible contact or support transparency signals.",
    "contact_information.present": "Contact information is present.",
    "contact_links.present": "Contact-related links are present.",
    "contact_presence": "The page has visible contact options.",
    "content.access_blocked_page": "The page looks like an access-blocked page.",
    "content.account_management": "The page includes account-management actions or language.",
    "content.account_verification_request": "The page asks the user to verify an account.",
    "content.account_verification_threat": "The page pressures the user with an account-verification threat.",
    "content.app_download_pressure": "The page pressures the user to download an app.",
    "content.article_format": "The page reads like an article or editorial page.",
    "content.brand_alignment": "The page content aligns with a specific brand identity.",
    "content.brand_consistency": "Brand signals in the content appear consistent.",
    "content.brand_impersonation": "The page content appears to impersonate another brand or site.",
    "content.brand_lookalike": "The page appears to mimic a known brand closely.",
    "content.brand_mismatch": "The page branding does not match other page signals.",
    "content.business_context": "The page appears to describe a business or service context.",
    "content.call_to_action": "The page prominently asks the user to take action.",
    "content.contact_details_present": "Contact details are included in the page content.",
    "content.contact_email.free_provider": "The contact email uses a free email provider.",
    "content.contact_forms": "The page includes forms for contacting the site.",
    "content.contact_support": "The page includes contact or support language.",
    "content.cookie_consent": "The page includes cookie-consent language.",
    "content.cookie_notice": "The page includes a cookie notice.",
    "content.copycat_branding": "The page uses copycat branding.",
    "content.credential_collection": "The page collects account credentials or other sensitive access data.",
    "content.credential_prompt": "The page prompts the user for credentials.",
    "content.credentials_prompt": "The page asks for login-style credentials.",
    "content.directory_listing": "The page looks like a directory or listing page.",
    "content.disclaimer": "The page includes disclaimer language.",
    "content.disclosure": "The page includes disclosure language.",
    "content.download_prompt": "The page prompts the user to download something.",
    "content.error_page": "The page looks like an error page.",
    "content.external_links": "The page includes links to external sites.",
    "content.file_lure_terms": "The page uses document, invoice, or file-lure language.",
    "content.financial_services_site": "The page presents financial-service-like content.",
    "content.generic_notice": "The page mostly shows a generic notice rather than normal content.",
    "content.help_portal": "The page looks like a help or support portal.",
    "content.human_verification_prompt": "The page asks the user to complete a human-verification step.",
    "content.impersonation_claim": "The page makes an impersonation-style identity claim.",
    "content.impersonation_message": "The page contains impersonation-like messaging.",
    "content.informational_page": "The page appears informational rather than transactional.",
    "content.installer_prompt": "The page prompts the user to install software or an app.",
    "content.language_mix": "The page mixes multiple languages or language artifacts.",
    "content.login_form": "The page contains a login form.",
    "content.login_form_password_only": "The login form focuses heavily on password entry.",
    "content.login_form_present": "A login form is visibly present.",
    "content.login_prompt": "The page prompts the user to log in.",
    "content.login_signup_prompts": "The page includes login or signup prompts.",
    "content.maintenance_lure": "The page uses maintenance or service-alert lure language.",
    "content.marketing_language": "The page uses marketing-style language.",
    "content.minimal_error_page": "The page looks like a sparse error page.",
    "content.minimal_text": "The page has very little visible text.",
    "content.nonsensical_text": "The page text looks low-quality or nonsensical.",
    "content.official_copyright_claim": "The page claims official copyright or ownership.",
    "content.official_terms_present": "Official-looking terms or policy text is present.",
    "content.organization_contact_page": "The page looks like an organization contact page.",
    "content.organization_profile": "The page looks like an organization profile.",
    "content.payment_channel_pressure": "The page pressures the user toward a payment channel.",
    "content.placeholder_action": "The page includes a placeholder or incomplete action element.",
    "content.policy_links": "The page includes policy or legal links.",
    "content.pressure_urgency": "The page uses pressure or urgency language.",
    "content.privacy_notice": "The page includes a privacy notice.",
    "content.profile_controls": "The page includes profile or account-control elements.",
    "content.reassurance_language": "The page uses reassurance or trust-building language.",
    "content.security_claims": "The page makes self-described security claims.",
    "content.security_urgency": "The page combines security claims with urgency.",
    "content.service_directory": "The page looks like a service directory.",
    "content.site_functionality": "The page signals that normal site functionality may be incomplete.",
    "content.site_purpose": "The page presents a clear site purpose.",
    "content.social_engineering_offer": "The page uses offer-style social-engineering language.",
    "content.social_proof_comments": "The page includes comments, reviews, or social-proof cues.",
    "content.support_contact_page": "The page looks like a support or contact page.",
    "content.third_party_security_reference": "The page references third-party security or trust services.",
    "content.trust_language": "The page uses trust-building language.",
    "content.urgency_language": "The page uses urgency language.",
    "content.urgent_checkout_flow": "The page pushes an urgent checkout flow.",
    "content.urgent_financial_notice": "The page shows an urgent financial notice.",
    "content.urgent_payment_request": "The page urgently asks for payment.",
    "content.verification_page_language": "The page uses verification-oriented language.",
    "cookie_banner": "A cookie banner is present.",
    "credential_collection": "The page collects credentials.",
    "credential_fields": "Credential-related fields are present.",
    "disclosure.present": "Disclosure text is present.",
    "domain.consistent_branding": "The domain appears consistent with the displayed branding.",
    "domain.final_host_mismatch": "The final host differs from the originally observed host.",
    "domain.impersonation_pattern": "The domain name shows impersonation-like patterns.",
    "domain.lookalike_branding": "The domain looks like it is imitating a known brand.",
    "domain.random_subdomain": "The site uses an unusual or random-looking subdomain.",
    "domain.reputation_like_pattern": "The domain pattern looks low-reputation or disposable.",
    "domain.self_references": "The page mostly links back to its own domain.",
    "embedded_frame": "The page includes an embedded frame.",
    "embedded_iframes": "The page uses embedded iframes.",
    "external_account_links": "The page links to external account destinations.",
    "external_advertising": "The page loads external advertising services.",
    "external_brand_asset": "The page loads brand-related assets from an external domain.",
    "external_install_link": "The page includes an external install or app-download link.",
    "external_integration": "The page relies on external integrations.",
    "external_link_mismatch": "An external link does not align with the surrounding context.",
    "external_links.profile": "The page links to external profile pages.",
    "external_links.social_profiles": "The page links to social-profile destinations.",
    "external_login_portal": "The page sends the user to an external login portal.",
    "external_login_redirect": "The page redirects login activity to another site.",
    "external_resource_loading": "The page loads resources from external domains.",
    "external_resource_mix": "The page mixes resources from multiple outside domains.",
    "external_resources.analytics_ads": "The page loads analytics or ad resources from third parties.",
    "external_trusted_integrations": "The page uses trusted third-party integrations, such as analytics or support widgets.",
    "external_script": "The page loads an external script.",
    "external_script.smtpjs": "The page loads an external SMTP/email script.",
    "external_script_dependencies": "The page depends on third-party scripts.",
    "form.absence": "No form is present on the page.",
    "form.action": "This refers to the form submission target or action.",
    "form.action_domain_mismatch": "A form submits to a domain that does not match the page.",
    "form.action_domain_same_site": "A form submits within the same site.",
    "form.action_external_application_endpoint": "A form submits to an external application endpoint.",
    "form.action_internal_path": "A form submits to an internal path on the same site.",
    "form.action_mismatch": "The form action does not align with the rest of the page.",
    "form.action_placeholder": "The form action looks like a placeholder.",
    "form.action_relative": "The form uses a relative action path.",
    "form.action_relative_external_like": "The form action looks relative but behaves like an external target.",
    "form.action_self_submit": "The form submits back to the same page.",
    "form.auth_fields": "Authentication-related form fields are present.",
    "form.auth_present": "An auth-related form is present.",
    "form.collects_credentials": "The form collects user credentials.",
    "form.collects_credentials_multiple_types": "The form collects multiple kinds of sensitive credential data.",
    "form.collects_personal_data": "The form collects personal data.",
    "form.collects_sensitive_identity": "The form collects identity-sensitive information.",
    "form.contact_and_quote": "The form looks like a contact or quote request form.",
    "form.credential_fields": "Credential-related fields are visible in the form.",
    "form.credentials_collection": "The form is used to collect credentials.",
    "form.credentials_like_inputs": "The form inputs resemble a login or credential form.",
    "form.credentials_login_form": "The form looks like a credentials-based login form.",
    "form.credentials_prompt": "The form prompts the user for credentials.",
    "form.credentials_request": "The form requests credentials.",
    "form.credentials_requested": "Credentials are being requested through the form.",
    "form.data_capture": "The form captures user-provided data.",
    "form.data_collection": "The form collects user data.",
    "form.data_collection_scope": "The form collects a notable amount of data.",
    "form.email_capture": "The form captures an email address.",
    "form.email_login": "The form supports email-based login.",
    "form.external_submission_endpoint": "The form submits to an external endpoint.",
    "form.external_submission_target": "The form target is external to the site.",
    "form.fields.email_only": "The form primarily asks for an email address.",
    "form.final_step_urgency": "The form uses final-step urgency language.",
    "form.identity_capture": "The form captures identity-related information.",
    "form.input_types": "This refers to the types of inputs present in the form.",
    "form.intent": "This refers to the apparent purpose of the form.",
    "form.login_action": "The form action looks tied to a login flow.",
    "form.login_action_path": "The form submits to a login-related path.",
    "form.login_credentials": "The form collects login credentials.",
    "form.login_fields": "The form contains standard login fields.",
    "form.login_presence": "A login form is present.",
    "form.observed_absence": "No relevant form was observed.",
    "form.password_field_present": "A password field is present.",
    "form.password_input_present": "The form includes a password input.",
    "form.password_login": "The form supports password-based login.",
    "form.requested_credentials": "The form requests credentials.",
    "form.requests_sms_verification_code": "The form asks for an SMS verification code.",
    "form.security_challenge": "The form includes a security challenge step.",
    "form.security_controls": "The form includes security-related controls.",
    "form.urgency_language": "The form uses urgency language.",
    "form.verification_prompt": "The form prompts the user to verify identity or access.",
    "forms.checkout_like": "The page includes a checkout-like form.",
    "forms.contact_options": "The page offers contact form options.",
    "forms.login_presence": "Login forms were observed.",
    "forms.login_register_presence": "Login or registration forms are present.",
    "forms.newsletter_signup": "A newsletter signup form is present.",
    "forms.total_observed": "This counts the number of observed forms.",
    "hosting.platform_branding": "The page shows branding from a hosting or site-builder platform.",
    "http.redirect_nature": "The redirect behavior looks like normal HTTP handling.",
    "https.redirect_present": "The site redirects users to HTTPS.",
    "iframe.advertising": "An advertising iframe is present.",
    "iframe.document_viewer": "The page includes an iframe document viewer.",
    "iframe.editor_embed": "The page includes an embedded editor iframe.",
    "iframe.external_src": "An iframe loads content from an external source.",
    "iframe.hidden_or_overlay": "The page contains a hidden or overlay-style iframe.",
    "iframe.javascript_src": "An iframe source is driven by JavaScript-like behavior.",
    "iframe.live_chat": "The page includes a live-chat iframe.",
    "iframe.live_chat_widget": "A live-chat widget iframe is present.",
    "iframe.maps_embed": "The page embeds a map iframe.",
    "iframe.media_player": "The page embeds a media player iframe.",
    "iframe.presence": "An iframe is present on the page.",
    "iframe.third_party_background": "A third-party iframe runs in the background.",
    "iframes.absent": "No iframes were observed.",
    "iframes.advertising_embeds": "The page includes advertising iframe embeds.",
    "iframes.none": "No iframes are present.",
    "iframes.total_observed": "This counts the number of observed iframes.",
    "language_and_branding_consistency": "The page language appears consistent with the branding.",
    "link.external_login_destination": "A link points to an external login destination.",
    "link.duplicate_local_hrefs": "Multiple links repeat the same local destination.",
    "link_destination": "This refers to where a link leads.",
    "linkage_to_external_login_targets": "Login-related actions lead to an external target.",
    "login.form_presence": "A login form is present.",
    "login_or_payment_absence": "No login or payment flow is present.",
    "login_present": "Login functionality is present.",
    "login_prompt.emphasis": "The page strongly emphasizes logging in.",
    "login_form_credentials": "The page uses a credential-collecting login form.",
    "login_form_presence": "A login form is present.",
    "meta.author_claim": "Metadata includes an author claim.",
    "meta.author_consistency": "The author metadata appears consistent with the page.",
    "meta.brand_misspelling": "Metadata includes a misspelled brand reference.",
    "meta.canonical_mismatch": "Canonical metadata does not match the observed page.",
    "meta.description.brand_impersonation_style": "The meta description uses brand-impersonation style language.",
    "meta.description.generic_cra": "The meta description looks generic or templated.",
    "meta.description.keyword_stuffing": "The meta description appears keyword-stuffed.",
    "meta.description_mismatch": "The meta description does not match the page content well.",
    "meta.generator": "Metadata reveals the site generator or CMS.",
    "meta.generator_indicator": "The page exposes generator metadata.",
    "meta.noindex_nofollow": "Robots metadata asks search engines not to index or follow the page.",
    "meta.og_image_external": "The Open Graph image is hosted externally.",
    "meta.og_image_external_mismatch": "The Open Graph image host differs from the site domain.",
    "meta.og_image_suspicious_source": "The Open Graph image comes from a suspicious source.",
    "meta.og_url_mismatch": "The Open Graph URL does not match the page URL.",
    "meta.robots.noindex_nofollow": "Robots metadata asks search engines not to index or follow the page.",
    "meta.robots_noindex": "The robots tag includes a noindex directive.",
    "meta.robots_noindex_nofollow": "The robots tag includes noindex and nofollow directives.",
    "meta.security_tokens": "Metadata exposes security-token-related fields.",
    "navigation.account_links": "The page includes account-related navigation.",
    "navigation.external_accounts": "Account-related navigation leads off-site.",
    "navigation.external_support_links": "Support links point to external destinations.",
    "navigation.internal_links": "The page includes internal links.",
    "navigation.links": "The page shows standard navigation links.",
    "navigation.redirects": "The page involves redirects during navigation.",
    "navigation.site_links": "The page includes normal site-navigation links.",
    "navigation.site_structure": "The page shows a normal site structure.",
    "navigation_and_support_links": "The page includes navigation and support links.",
    "navigation_scope": "This reflects how broad or narrow the site navigation is.",
    "official_site_disclosure": "The page includes an official-style disclosure statement.",
    "outbound.external_links": "The page contains outgoing external links.",
    "page.access_blocked_page": "The page appears blocked or restricted.",
    "page.anchor_presence": "The page contains links.",
    "page.anchors.count": "This counts the number of anchors on the page.",
    "page.anchors_absent": "No anchors were observed on the page.",
    "page.authentication_form": "An authentication form is present.",
    "page.authentication_forms": "Authentication-related forms are present.",
    "page.brand_consistency": "The page branding appears consistent.",
    "page.brand_imitation": "The page imitates another brand.",
    "page.brand_impersonation": "The page appears to impersonate a brand or service.",
    "page.brand_impersonation_language": "The page uses language typical of impersonation.",
    "page.brand_like_footprint": "The page has the footprint of a known brand experience.",
    "page.brand_like_title": "The title looks like it references a known brand.",
    "page.brand_mimicry": "The page mimics the look or identity of another brand.",
    "page.brand_title_mismatch": "The page title does not match the domain or branding context.",
    "page.branding_absence": "Expected branding is absent from the page.",
    "page.branding_and_disclosure_mix": "Branding and disclosure signals are mixed together.",
    "page.branding_and_legal_footer": "The page includes branding with a legal-style footer.",
    "page.branding_consistency": "The page branding appears internally consistent.",
    "page.branding_discrepancy": "There is a discrepancy in the page branding.",
    "page.branding_inconsistency": "Branding on the page is inconsistent.",
    "page.branding_mismatch": "Page branding does not match other signals.",
    "page.branding_presence": "Branding is visibly present on the page.",
    "page.chat_widget": "The page includes a chat widget.",
    "page.clone_login_layout": "The page layout looks like a cloned login page.",
    "page.contact_form": "A contact form is present.",
    "page.contact_options": "The page includes contact options.",
    "page.content.imitation_login": "The page content resembles an imitation login page.",
    "page.content.login_prompt": "The page content prompts the user to log in.",
    "page.content.news_article": "The page content looks like a news article.",
    "page.content.support_links": "The page includes support-related links.",
    "page.content.urgency_social_proof": "The page mixes urgency with social-proof messaging.",
    "page.content_business_context": "The page looks like it serves a business context.",
    "page.content_brand_impersonation": "The page content suggests brand impersonation.",
    "page.content_article": "The page looks like an article page.",
    "page.content_business_context": "The page looks business-oriented.",
    "page.content.coherent_profile_page": "The page looks like a coherent profile page.",
    "page.content.community_support": "The page includes community or support content.",
    "page.credential_collection_form": "The page includes a credential-collection form.",
    "page.credential_like_form_prompt": "The page prompts the user with a credential-like form.",
    "page.disclaimer.testing_only": "The page includes a testing-only disclaimer.",
    "page.disclaimer_links": "The page includes disclaimer links.",
    "page.identity_verification_prompt": "The page prompts the user to verify identity.",
    "page.language_context": "The page suggests a specific language context.",
    "page.language_localization": "The page includes localization or language selectors.",
    "page.login_destination": "The page points the user toward a login destination.",
    "page.login_form": "A login form is present on the page.",
    "page.login_form_credentials": "The page login form collects credentials.",
    "page.login_form_present": "A login form is visible on the page.",
    "page.login_over_http": "The page presents login over plain HTTP.",
    "page.login_prompt_content": "The page content strongly prompts the user to log in.",
    "page.login_style_language": "The page uses language typical of a login interface.",
    "page.login_theme": "The page has a login-page theme.",
    "page.multilingual_login": "The page combines login prompts with multiple languages.",
    "page.navigation_and_contact": "The page includes navigation and contact options.",
    "page.privacy_links": "The page includes privacy-related links.",
    "page.redirects": "The page involves redirects.",
    "page.rendering_incomplete_or_script_dependent": "The page appears incompletely rendered or highly script-dependent.",
    "page.requested_account_action": "The page asks the user to take an account-related action.",
    "page.risk_disclosure": "The page includes risk-disclosure language.",
    "page.security_notice": "The page includes a security notice.",
    "page.security_tokens_present": "Security-token elements are present.",
    "page.security_verification_challenge": "The page includes a security-verification challenge.",
    "page.standard_login_interface": "The page looks like a standard login interface.",
    "page.title.brand_appeal_language": "The title uses language appealing to a known brand.",
    "page.title.login_ui": "The title suggests a login interface.",
    "page.title_brand_login": "The title combines brand and login language.",
    "page.title_branding": "The title contains branding language.",
    "page.title_matches_branding": "The title matches the page branding.",
    "page.title_misleading_branding": "The title uses misleading branding.",
    "page.title_generic_verification": "The title suggests a generic verification page.",
    "page.title_login_prompt": "The title acts as a login prompt.",
    "page.urgent_deadline": "The page emphasizes an urgent deadline.",
    "page.urgency_language": "The page uses urgency language.",
    "page_branding": "The page includes clear branding.",
    "page_branding_consistency": "The page branding is consistent.",
    "page_content.account_controls": "The page includes account-control content.",
    "page_content.business_presence": "The page shows signs of a business presence.",
    "page_content.login_prompt": "The page content prompts the user to log in.",
    "page_content_urgency": "The page content uses urgency language.",
    "page_content_article_format": "The page content is article-like in format.",
    "page_content_article_layout": "The page content follows an article-like layout.",
    "page_disclosure_links": "The page includes disclosure links.",
    "page_language_mismatch": "The page language does not match the expected context.",
    "page_login_form": "A login form is present.",
    "page_login_prompt": "The page prompts the user to log in.",
    "page_spoofed_branding": "The page uses spoofed branding.",
    "page_title_generic_login": "The title looks like a generic login page.",
    "page_title_generic_mail_login": "The title looks like a generic webmail login.",
    "page_title_login_portal": "The title looks like a login portal.",
    "password_reset_and_registration_links": "The page includes password reset or registration links.",
    "payment_and_withdrawal_instructions": "The page includes payment or withdrawal instructions.",
    "payment_channel_promotion": "The page promotes a payment channel.",
    "privacy_banner": "A privacy banner is present.",
    "privacy_policy_presence": "A privacy policy is present.",
    "protocol.redirect_to_https": "The site redirects users toward HTTPS.",
    "publisher_metadata": "The page exposes publisher-related metadata.",
    "resource.analytics_present": "Analytics resources are present.",
    "resource.branding_assets": "The page loads branding-related assets.",
    "resource.builder_hosting": "The page appears hosted on a site-builder platform.",
    "resource.cross_domain_assets": "Assets are loaded from other domains.",
    "resource.cross_domain_brand_assets": "Brand-related assets are loaded cross-domain.",
    "resource.domain_consistency": "Resource domains appear consistent with the site.",
    "resource.external_brand_asset": "A brand asset is loaded from an external domain.",
    "resource.external_brand_assets": "Brand assets are loaded from external domains.",
    "resource.external_domain_mix": "Resources come from a mix of outside domains.",
    "resource.external_email_library": "The page loads an external email-related library.",
    "resource.external_email_script": "The page loads an external email-related script.",
    "resource.external_image": "The page loads an image from an external domain.",
    "resource.external_script": "The page loads a script from an external domain.",
    "resource.external_script_domain": "The script host differs from the site domain.",
    "resource.external_webmail_asset": "The page loads an external webmail-style asset.",
    "resource.favicon_branding": "The favicon carries branding signals.",
    "resource.first_party_assets": "The page uses first-party assets.",
    "resource.generic_hosting": "The site appears to use generic hosting infrastructure.",
    "resource.host_consistency": "Resources come from expected and coherent hosts.",
    "resource.hosting_cdn": "The page relies on CDN or hosting infrastructure.",
    "resource.hosting_consistency": "Hosting-related assets appear consistent.",
    "resource.known_services": "The page uses known third-party services.",
    "resource.legitimate_asset_mix": "The asset mix looks normal for a legitimate site.",
    "resource.legitimate_static_assets": "The page includes normal static assets.",
    "resource.legitimate_third_party_services": "The page uses common legitimate third-party services.",
    "resource.loaders": "The page includes script or asset loaders.",
    "resource.local_assets": "The page uses local assets.",
    "resource.official_asset_usage": "The page uses official-looking brand assets.",
    "resource.official_cdn_usage": "The page uses official CDN resources.",
    "resource.official_site_assets": "The page uses assets associated with an official site.",
    "resource.official_site_structure": "The asset structure resembles an official site.",
    "resource.profile.standard": "The resource profile looks standard for a normal site.",
    "resource.reputation_style": "The resource profile suggests a recognizable hosting style.",
    "resource.script_external_smtpjs": "The page loads an external SMTPJS script.",
    "resource.script_third_party_unusual": "The page loads unusual third-party scripts.",
    "resource.stack": "This reflects the page’s web stack or tooling profile.",
    "resource.standard_platforms": "The page uses standard web platforms.",
    "resource.third_party_ad_analytics": "The page loads third-party ad or analytics services.",
    "resource.third_party_ads": "The page loads third-party advertising assets.",
    "resource.third_party_ads_analytics": "The page uses third-party ad or analytics resources.",
    "resource.third_party_analytics": "The page uses third-party analytics.",
    "resource.third_party_assets": "The page uses assets from third parties.",
    "resource.third_party_delivery_domain": "Resources are delivered from a third-party host.",
    "resource.third_party_image": "The page loads a third-party image.",
    "resource.third_party_integrations": "The page uses third-party integrations.",
    "resource.third_party_mixed_assets": "The page mixes assets from multiple third parties.",
    "resource.third_party_scripts": "The page uses third-party scripts.",
    "resource.third_party_services": "The page uses third-party services.",
    "resource.wordPress_assets": "The page uses WordPress-related assets.",
    "resource_brand_consistency": "Brand-related resources appear consistent.",
    "resource_domain_mismatch": "Resource domains do not match the site well.",
    "resource_first_party_assets": "The page uses first-party assets.",
    "resource_loading": "This refers to the page’s resource-loading behavior.",
    "resource_profile": "This refers to the page’s overall resource profile.",
    "resource_structure": "This refers to the structure of loaded resources.",
    "resources.brand_assets": "The page loads brand-related assets.",
    "resources.brand_consistency": "Brand-related resources appear consistent.",
    "resources.common_analytics": "The page uses common analytics tooling.",
    "resources.external_brand_assets": "The page loads brand assets from external domains.",
    "resources.external_dependencies": "The page depends on external resources.",
    "resources.external_image": "The page loads external images.",
    "resources.external_infrastructure": "The page relies on external infrastructure.",
    "resources.external_script_usage": "The page uses external scripts.",
    "resources.external_scripts": "The page loads scripts from external domains.",
    "resources.external_smtp_library": "The page loads an external SMTP library.",
    "resources.first_party_assets": "The page uses first-party assets.",
    "resources.local_assets": "The page uses local assets.",
    "resources.minimal_page_assets": "The page uses a very small set of assets.",
    "resources.official_infrastructure": "The page uses infrastructure associated with a legitimate provider.",
    "resources.official_static_assets": "The page uses official-looking static assets.",
    "resources.script_src_sample.external_analytics": "The sampled scripts include external analytics.",
    "resources.standard_web_stack": "The page appears to use a standard web stack.",
    "resources.storefront_assets": "The page uses storefront or shopping-platform assets.",
    "resources.third_party_ads": "The page loads third-party ads.",
    "resources.third_party_scripts": "The page uses third-party scripts.",
    "security.claim_overlay": "The page overlays a security-related claim.",
    "security.csp_upgrade_insecure_requests": "The page signals CSP upgrade-insecure-requests behavior.",
    "security.csrf_tokens_present": "CSRF-token indicators are present.",
    "security.https": "The page is served over HTTPS.",
    "security.notice_and_policy_links": "The page includes security, policy, or legal links.",
    "security.transport": "This reflects the page transport security, such as HTTPS.",
    "security.turnstile_present": "Cloudflare Turnstile or similar challenge is present.",
    "security.validation_presence": "The page includes security validation signals.",
    "security_indicator.cookies_notice": "The page shows a cookies/security notice.",
    "security_indicators.https": "The page is served over HTTPS.",
    "security_policy_links": "Privacy or terms links are present.",
    "security_privacy_elements": "The page includes security or privacy-related elements.",
    "security_related_metadata": "The page exposes security-related metadata.",
    "security_widgets": "The page includes security or challenge widgets.",
    "security_widgets.present": "A security-related widget is present.",
    "site.account_actions": "The site includes account-related actions.",
    "site.brand_catalog_content": "The site content catalogs a brand or product offering.",
    "site.branding_and_content_consistency": "The site branding matches the content.",
    "site.branding_consistency": "Site branding appears consistent.",
    "site.branding_generic": "The site branding is generic rather than distinctive.",
    "site.checkout_related_forms": "The site includes checkout-related forms.",
    "site.contact_and_navigation_structure": "The site shows normal contact and navigation structure.",
    "site.contact_info_presence": "The site provides contact information.",
    "site.contact_subscription_forms": "The site includes contact or subscription forms.",
    "site.content_business_like": "The site content looks business-like.",
    "site.content_business_service": "The site content describes business services.",
    "site.domain_reputation_signals": "The domain shows reputation-like signals.",
    "site.ecommerce_checkout_flow": "The site looks like it supports ecommerce checkout.",
    "site.identity.clear_branding": "The site clearly presents its identity or brand.",
    "site.navigation_and_branding": "The site has coherent navigation and branding.",
    "site.security_integration": "The site integrates security-related services.",
    "site.third_party_scripts": "The site uses third-party scripts.",
    "site.content_coherence": "The page content and structure look coherent for a legitimate site.",
    "site_metadata.localization": "Metadata includes localization information.",
    "site_metadata.social_proof": "Metadata or content includes social-proof cues.",
    "support.widget.iframe": "A support widget is embedded through an iframe.",
    "support_elements_present": "Support-related elements are present.",
    "third_party_integrations.recaptcha": "The page uses reCAPTCHA or a similar third-party challenge.",
    "title.brand_impersonation": "The page title looks like brand impersonation.",
    "title.brand_impersonation_pattern": "The title follows a brand-impersonation pattern.",
    "title.brand_login_mimicry": "The title combines brand and login language in a mimicry pattern.",
    "title.branding_consistency": "The title is consistent with the page branding.",
    "title.clone_like_branding": "The title looks like cloned or copied branding.",
    "title.generic_login": "The title looks like a generic login page.",
    "title.generic_login_branding": "The title combines generic login wording with branding.",
    "title.generic_login_theme": "The title has a generic login-page theme.",
    "title.login_claim": "The title claims the page is a login portal.",
    "title.login_impersonation": "The title suggests a login-related impersonation.",
    "title.login_keyword": "The title contains login-related keywords.",
    "title.login_like_impersonation": "The title looks like an impersonating login page.",
    "title.login_lure": "The title acts like a login lure.",
    "title.login_theme": "The title has a login-related theme.",
    "title.matches_login_page": "The title matches a login-page context.",
    "tracking_scripts_present": "Tracking or analytics scripts are present.",
    "ui.live_chat_widget": "The page includes a live-chat widget.",
    "ui.urgency_language": "The visible interface uses urgency language.",
    "urgency_security_notice": "The page combines urgency with a security notice.",
    "url.brand_like_path": "The URL path contains brand-like terms.",
    "url.domain": "This refers to the site domain itself.",
    "url.domain_mismatch": "The domain does not align with the page identity or displayed brand.",
    "url.domain_age_hint": "The URL suggests a young or temporary domain.",
    "url.domain_age_indicator": "The domain appears age-related or newly created.",
    "url.domain_age_like_pattern": "The domain pattern resembles a newly created or disposable site.",
    "url.domain_consistency": "The observed and final URLs are consistent with each other.",
    "url.domain_deception_potential": "The domain has signs of deceptive naming.",
    "urgency_security_notice": "The page mixes urgency with security messaging.",
    "page.content_consistency": "The page content is internally consistent and matches an expected site purpose.",
    "page.content_topic": "The page content clearly centers on a specific, understandable topic.",
    "security_claim_text": "The page includes self-described security language or trust claims.",
}


TOKEN_EXPLANATIONS: dict[str, str] = {
    "account": "account-related",
    "action": "action-related",
    "ads": "advertising",
    "adult": "adult-content",
    "affiliate": "affiliate",
    "analytics": "analytics-related",
    "anchor": "link-related",
    "anchors": "links",
    "antibot": "anti-bot",
    "app": "app-related",
    "article": "article-like",
    "assets": "assets/resources",
    "auth": "authentication-related",
    "author": "author-related",
    "banner": "banner-related",
    "betting": "betting-related",
    "bot": "bot-check",
    "brand": "brand-related",
    "branding": "branding-related",
    "business": "business-related",
    "captcha": "captcha-related",
    "catalog": "catalog-related",
    "category": "category-related",
    "challenge": "challenge-related",
    "chat": "chat-related",
    "checkout": "checkout-related",
    "claim": "claim-related",
    "clone": "clone-like",
    "cms": "CMS-related",
    "comment": "comment-related",
    "community": "community-related",
    "consistency": "consistency",
    "contact": "contact-related",
    "content": "content-related",
    "cookie": "cookie-related",
    "copyright": "copyright-related",
    "credential": "credential-related",
    "credentials": "credential-related",
    "csrf": "CSRF-related",
    "data": "data-related",
    "description": "description-related",
    "destination": "destination-related",
    "directory": "directory-related",
    "disclaimer": "disclaimer-related",
    "disclosure": "disclosure-related",
    "document": "document-related",
    "domain": "domain-related",
    "download": "download-related",
    "editorial": "editorial-related",
    "email": "email-related",
    "embed": "embedded-content",
    "error": "error-page",
    "external": "external",
    "favicon": "favicon-related",
    "fields": "fields",
    "file": "file-related",
    "footer": "footer-related",
    "form": "form-related",
    "generator": "generator-related",
    "help": "help-related",
    "hidden": "hidden",
    "host": "host-related",
    "hosting": "hosting-related",
    "http": "HTTP-related",
    "https": "HTTPS-related",
    "identity": "identity-related",
    "iframe": "iframe-related",
    "image": "image-related",
    "impersonation": "impersonation",
    "index": "indexing-related",
    "information": "information-related",
    "install": "installation-related",
    "integration": "integration-related",
    "internal": "internal",
    "keyword": "keyword-related",
    "language": "language-related",
    "legal": "legal-related",
    "link": "link-related",
    "links": "link-related",
    "live": "live-service",
    "loading": "loading-related",
    "localization": "localization-related",
    "login": "login-related",
    "lookalike": "lookalike",
    "mail": "mail-related",
    "maintenance": "maintenance-related",
    "maps": "maps-related",
    "marketing": "marketing-related",
    "meta": "metadata-related",
    "metadata": "metadata-related",
    "mismatch": "mismatch",
    "navigation": "navigation-related",
    "news": "news-related",
    "nofollow": "nofollow",
    "noindex": "noindex",
    "notice": "notice-related",
    "observed": "observed",
    "official": "official-looking",
    "offsite": "off-site",
    "og": "Open Graph",
    "organization": "organization-related",
    "password": "password-related",
    "payment": "payment-related",
    "placeholder": "placeholder-related",
    "policy": "policy-related",
    "presence": "presence",
    "privacy": "privacy-related",
    "profile": "profile-related",
    "prompt": "prompt-related",
    "redirect": "redirect-related",
    "register": "registration-related",
    "reputation": "reputation-like",
    "resource": "resource-related",
    "resources": "resource-related",
    "recovery": "recovery-related",
    "review": "review-related",
    "risk": "risk-related",
    "robots": "robots-metadata",
    "script": "script-related",
    "security": "security-related",
    "service": "service-related",
    "shipping": "shipping-related",
    "signup": "signup-related",
    "site": "site-related",
    "social": "social-related",
    "smtp": "email-delivery-related",
    "spoofed": "spoofed",
    "standard": "standard-looking",
    "storefront": "storefront-related",
    "structure": "structure-related",
    "submission": "submission-related",
    "support": "support-related",
    "terms": "terms-related",
    "third": "third-party",
    "topic": "topic-related",
    "tracking": "tracking-related",
    "transport": "transport-security",
    "trust": "trust-related",
    "turnstile": "Turnstile-related",
    "urgent": "urgency-related",
    "urgency": "urgency-related",
    "url": "URL-related",
    "user": "user-related",
    "verification": "verification-related",
    "visible": "visible",
    "widget": "widget-related",
}


PREFIX_BUILDERS: list[tuple[re.Pattern[str], Callable[[re.Match[str]], str]]] = [
    (
        re.compile(r"^content\.brand_(.+)$"),
        lambda m: f"Content shows a brand-related signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^page\.brand_(.+)$"),
        lambda m: f"Page-level branding signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^form\.(.+)$"),
        lambda m: f"Form-related signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^meta\.(.+)$"),
        lambda m: f"Metadata signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^resource[s]?\.(.+)$"),
        lambda m: f"Resource-loading signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^anchor[s]?\.(.+)$"),
        lambda m: f"Link-related signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^page\.(.+)$"),
        lambda m: f"Page-level signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^url\.(.+)$"),
        lambda m: f"URL-related signal: {humanize_tokens(m.group(1))}.",
    ),
    (
        re.compile(r"^navigation\.(.+)$"),
        lambda m: f"Navigation signal: {humanize_tokens(m.group(1))}.",
    ),
]


def normalize_feature_id(feature_id: str) -> str:
    return re.sub(r"\s+", "", (feature_id or "").strip())


def humanize_tokens(raw: str) -> str:
    parts = [part for part in re.split(r"[._]+", raw.strip()) if part]
    words: list[str] = []
    for part in parts:
        words.append(TOKEN_EXPLANATIONS.get(part.lower(), part.replace("-", " ")))
    text = " ".join(words).strip()
    text = re.sub(r"\s+", " ", text)
    return text


def fallback_explanation(feature_id: str) -> str:
    normalized = normalize_feature_id(feature_id)
    for pattern, builder in PREFIX_BUILDERS:
        match = pattern.match(normalized)
        if match:
            return builder(match)

    human = humanize_tokens(normalized)
    human = human[:1].upper() + human[1:] if human else normalized
    if not human.endswith("."):
        human += "."
    return human


def translate_feature_id(feature_id: str) -> str:
    """Return a short human-understandable explanation for a feature id.

    The function prefers exact translations for common or high-signal feature
    ids and falls back to rule-based translation for unseen ids.
    """

    normalized = normalize_feature_id(feature_id)
    if not normalized:
        return "Unknown feature."
    return EXACT_EXPLANATIONS.get(normalized, fallback_explanation(normalized))
